Update tools

diff --git a/tools/bin/build-gtest b/tools/bin/build-gtest
--- a/tools/bin/build-gtest
+++ b/tools/bin/build-gtest
@@ -2,6 +2,7 @@
 #
 # Install GoogleTest under current project.
 # IMPORTANT; Must be run inside project git repository.
+VERSION=1.3
 if [[ "$!" =~ ^-{1,2}h(elp)?$ ]]; then
   cat <<'HELPTEXT'
 Name
@@ -23,14 +24,18 @@ Must be run inside project git repository.
 
 HELPTEXT
   exit 0;
+elif [[ "$1" =~ ^-{1,2}version$ ]]; then
+  echo "build-gtest version ${VERSION}"
+  exit 0;
 fi
 
 
-LIBNAME="GoogleTest"
+TOOL_NAME="GoogleTest"
+TOOL_DESC="${TOOL_NAME} library"
 GIT_URL="https://github.com/google/googletest.git"
 
 function Die() {
-  echo "FAILED to build and install ${LIBNAME}! $*" 1>&2
+  echo "FAILED to build and install ${TOOL_DESC}! $*" 1>&2
   exit 1
 }
 function Realpath() {
@@ -38,16 +43,15 @@ function Realpath() {
   /usr/bin/perl '-MCwd(abs_path)' -le '$p=abs_path(join(q( ),@ARGV));print $p if -e $p' "$*"
 }
 
-TOOL_PATH="$(Realpath "$0")"
-echo "Attempting to build ${LIBNAME} using ${TOOL_PATH}"
-HERE="$(pwd)"
-if [[ "${HERE}" =~ .*/extern ]]; then
-  cd "${HERE/extern*/}" || Die "Trying to escape extern sub-directory failed"
+BUILD_PATH="$(Realpath "$0")"
+echo "Attempting to build ${TOOL_DESC} using ${BUILD_PATH}"
+INSTALL_DIR="$(find_extern -s)"
+if [[ -z "${INSTALL_DIR}" ]]; then
+  Report_fatal "Unable to locate required extern/include directory";
+  return 1
 fi
-WORKTREE_DIR="$(git rev-parse --show-toplevel)" || Die "Not in git repo"
 REPO_DIR="$(basename "${GIT_URL}" .git)"
-BUILD_DIR="build"
-INSTALL_DIR="${WORKTREE_DIR}/extern"
+BUILD_DIR="target/${TOOL_NAME}"
 mkdir -p "${INSTALL_DIR}"
 cd "${INSTALL_DIR}" || Die "Unable to enter ${INSTALL_DIR}"
 if [[ -d "${REPO_DIR}/.git" ]]; then
@@ -60,6 +64,6 @@ cd "${REPO_DIR}" || Die "Unable to enter ${REPO_DIR}"
 cmake -B "${BUILD_DIR}" -S . -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" || Die "Unable to configure cmake"
 cmake --build "${BUILD_DIR}" || Die "Failed to compile and link"
 cmake --install build || Die "Failed to install"
-echo "Successfully built ${LIBNAME}"
+echo "Successfully built ${TOOL_DESC}"
 
 # vim:nospell
diff --git a/tools/bin/build-systemc b/tools/bin/build-systemc
--- a/tools/bin/build-systemc
+++ b/tools/bin/build-systemc
@@ -2,76 +2,414 @@
 #
 # Steps to build and install SystemC
 #
-#| For help on options use --help or examine utils.bash
+#| For help on options use --help.
 #
-TOOL_BRIEF="$0 - build and install SystemC from github source"
+TOOL_BRIEF="build-systemc - build and install SystemC from github source"
+BUILD_SYSTEMC_VERSION="0.1.3"
 TOOL_NAME="SystemC"
 TOOL_INFO='Go to <https://accellera.org/downloads/standards/systemc> for more information.'
 # ${TOOL_SRC}/${TOOL_BASE} for full path to source
-TOOL_SRC="${HOME}/.local/src"
+TOOL_SRC=${HOME}/.portable-scripts/src
 TOOL_BASE="systemc"
 TOOL_URL="https://github.com/accellera-official/systemc.git"
-TOOL_VERS='master' # latest or 3.0 or 2.3.4
+TOOL_VERS='main' # latest or 3.0 or 2.3.4
 TOOL_CHECKOUT=""
 
-export TOOL_BRIEF TOOL_NAME TOOL_SRC TOOL_BASE TOOL_URL TOOL_INFO TOOL_VERS TOOL_CHECKOUT TOOL_PATCHES
-export SYSTEMC_HOME TOOL_SRC BUILD_DIR CLEAN CMAKE_INSTALL_PREFIX CMAKE_BUILD_TYPE CMAKE_APPLE_SILICON_PROCESSOR
+function Build_systemc()
+{
+    if [[ $# -eq 2 ]]; then
+      case "$2" in
+        -V|--version) printf 'build-systemc version %s\n' "${BUILD_SYSTEMC_VERSION}"; return 0 ;;
+        -h|-help|--help) HelpText; return 0 ;;
+        *) ;;
+      esac
+    fi
+    export TOOL_BRIEF TOOL_NAME TOOL_SRC TOOL_BASE TOOL_URL TOOL_INFO TOOL_VERS TOOL_CHECKOUT TOOL_PATCHES
+    export SYSTEMC_HOME BUILD_DIR CLEAN CMAKE_INSTALL_PREFIX CMAKE_BUILD_TYPE CMAKE_APPLE_SILICON_PROCESSOR
+
+    shift
+
+    export LOGFILE
+    SetupLogdir "$0"
+    local SCRIPT_PATH
+    SCRIPT_PATH="$(Realpath "$0")"
+    Report_info -cyn "Executing ${SCRIPT_PATH} (stand-alone)"
+
+    GetBuildOpts "$0" "$@"
+    TOOL_SRC="${SRC}"
+    ConfirmBuildOpts || exit
+
+    Create_and_Cd "${TOOL_SRC}" || exit
+    Report_info -grn "Obtaining ${TOOL_NAME} source"
+    GetSource_and_Cd "${TOOL_BASE}" "${TOOL_URL}" || exit
+    Select_version "${TOOL_VERS}" || exit
+
+    Report_info -grn "Building ${TOOL_NAME}"
+    Configure_tool || exit 1
+    Compile_tool || exit 1
+
+    if [[ -z "${NOINSTALL+x}" || "${NOINSTALL}" == "no" ]]; then
+      local systemc_version
+      systemc_version="$(Systemc_version_from_build)" || {
+        Report_fatal "Unable to determine SystemC version from built output"
+        exit 1
+      }
+      SYSTEMC_HOME="${INSTALL_DIR_EXPLICIT:+${INSTALL_DIR}}"
+      if [[ -z "${SYSTEMC_HOME}" ]]; then
+        SYSTEMC_HOME="${INSTALL_DIR}/systemc-${systemc_version}"
+      fi
+      export SYSTEMC_HOME
+      Check_registry_conflicts || exit 1
+      Install_tool || exit 1
+
+      # Optional clean up
+      if [[ "${CLEAN}" == 1 ]]; then
+        Report_info -red "Clean up"
+        cd "${TOOL_SRC}" || Report_fatal "Unable to enter source directory"
+        # shellcheck disable=SC2312
+        rm -fr "${TOOL_NAME}"* | Log
+      fi
+
+      Report_info -grn "Finished installation of ${TOOL_NAME} into ${SYSTEMC_HOME}"
+    else
+      Report_info -mag "Stopped shy of installing ${TOOL_NAME}"
+    fi
+
+    # Clean up
+    if [[ -n "${TMP}" ]]; then
+      rm -fr "${TMP}"
+    fi
+    if [[ -r "${LOGFILE}" ]]; then
+      if [[ -z "${TOOL_VERS}" ]]; then
+        TOOL_VERS="default"
+      fi
+      mv "${LOGFILE}" "${LOGFILE/.log/}-${TOOL_VERS}.log"
+    fi
+}
 
 function Realpath() {
   if [[ $# == 0 ]]; then set - .; fi
   /usr/bin/perl '-MCwd(abs_path)' -le '$p=abs_path(join(q( ),@ARGV));print $p if -e $p' "$*"
 }
 
-SCRIPTDIR="$(Realpath "$(dirname "$0")"/../bin)"
-if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  SCRIPTDIR="$(Realpath "${HOME}"/.local/bin)"
-fi
-if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  SCRIPTDIR="$(Realpath "$(dirname "$0")")"
-fi
-if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  printf "FATAL: Missing required source file '%s'\n" "${SCRIPTDIR}/utils.bash"
-  exit 1
-fi
+function _C() {
+    COLOR_CODE=""
+    [[ ${NOCOLOR:-0} == 1 ]] && return 0
+    local color
+    color="$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')"
+    case "${color}" in
+      none|off|-) COLOR_CODE=$'\033[0m' ;;
+      bold) COLOR_CODE=$'\033[1m' ;;
+      red) COLOR_CODE=$'\033[91m' ;;
+      grn|green) COLOR_CODE=$'\033[92m' ;;
+      ylw|yellow) COLOR_CODE=$'\033[93m' ;;
+      bg-yellow) COLOR_CODE=$'\033[43m' ;;
+      blu|blue) COLOR_CODE=$'\033[94m' ;;
+      mag) COLOR_CODE=$'\033[95m' ;;
+      cyn|cyan) COLOR_CODE=$'\033[96m' ;;
+      *) return 0 ;;
+    esac
+}
 
-export UTILS_VERSION
-# shellcheck disable=SC2250,SC1091
-source "$SCRIPTDIR/utils.bash"
+function Set_color() {
+    COLOR=""
+    local color
+    for color in "$@"; do
+      _C "${color}"
+      COLOR+="${COLOR_CODE}"
+    done
+}
 
-SetupLogdir "$0"
-SCRIPTPATH="$(Realpath "$0")"
-Report_info -cyn "Executing ${SCRIPTPATH} with utils.bash v${UTILS_VERSION}"
+function Log() {
+    [[ -z "${LOGFILE:-}" || ${NOLOG:-0} == 1 ]] && return 0
+    if [[ "$1" == -n ]]; then shift; printf '%s' "$*" >>"${LOGFILE}"; else printf '%s\n' "$*" >>"${LOGFILE}"; fi
+}
 
-GetBuildOpts "$0" "$@"
-CMAKE_INSTALL_PREFIX="${SYSTEMC_HOME}"
-ConfirmBuildOpts || exit
+function Echo() {
+    if [[ "$1" == -n ]]; then shift; printf '%s' "$*"; Log -n "$*"; else printf '%s\n' "$*"; Log "$*"; fi
+}
 
-Create_and_Cd "${TOOL_SRC}" || exit
-Report_info -grn "Obtaining ${TOOL_NAME} source"
-GetSource_and_Cd "${TOOL_BASE}" "${TOOL_URL}" || exit
-Select_version "${TOOL_VERS}" || exit
+function _do() {
+    if [[ -n "${NOTREALLY:-}" ]]; then
+      Set_color bold red; local prefix="${COLOR}"
+      Set_color none; local reset="${COLOR}"
+      Set_color mag; local magenta="${COLOR}"
+      Echo "${prefix}#${reset} ${magenta}$*${reset}"
+      return 0
+    fi
+    Set_color cyn; local cyan="${COLOR}"
+    Set_color none; local reset="${COLOR}"
+    Set_color bold blu; local command_color="${COLOR}"
+    Echo "${cyan}%${reset}${command_color} $*${reset}"
+    if [[ -n "${LOGFILE:-}" ]]; then
+      local output_file command_status
+      output_file="$(mktemp)"
+      "$@" >"${output_file}" 2>&1
+      command_status=$?
+      tee -a "${LOGFILE}" <"${output_file}"
+      rm -f "${output_file}"
+      return "${command_status}"
+    fi
+    "$@"
+}
 
-Report_info -grn "Building ${TOOL_NAME}"
-# shellcheck disable=SC2119,SC2312
-Configure_tool | Log
-# shellcheck disable=SC2119,SC2312
-Compile_tool   | Log
+function Report_info() {
+    local color=none
+    [[ "$1" == -* ]] && color="${1#-}" && shift
+    [[ ${VERBOSITY:-0} -lt 1 && ${color} == none ]] && return 0
+    Set_color "${color}"; local prefix="${COLOR}"
+    Set_color none; local reset="${COLOR}"
+    Echo "${prefix}$*${reset}"
+}
 
-if [[ -z "${NOINSTALL+x}" || "${NOINSTALL}" == "no" ]]; then
-  # shellcheck disable=SC2119,SC2312
-  Install_tool | Log
+function Report_warning() {
+    WARNINGS=$(( ${WARNINGS:-0} + 1 ))
+    Set_color bold ylw; local prefix="${COLOR}"
+    Set_color none; local reset="${COLOR}"
+    Echo "${prefix}Warning:${reset} $*${reset}" >&2
+}
 
-  # Optional clean up
-  if [[ "${CLEAN}" == 1 ]]; then
-    Report_info -red "Clean up"
-    cd "${TOOL_SRC}" || Report_fatal "Unable to enter source directory"
-    # shellcheck disable=SC2312
-    rm -fr "${TOOL_NAME}"* | Log
-  fi
+function Report_fatal() {
+    ERRORS=$(( ${ERRORS:-0} + 1 ))
+    Set_color bold red; local prefix="${COLOR}"
+    Set_color none; local reset="${COLOR}"
+    Echo "${prefix}Fatal:${reset} $*${reset}" >&2
+    return 1
+}
 
-  Report_info -grn "Finished installation of ${TOOL_NAME} into ${SYSTEMC_HOME}"
-else
-  Report_info -mag "Stopped shy of installing ${TOOL_NAME}"
-fi
+function Systemc_version_from_tree() {
+    local tree="$1" header
+    header="$(find "${tree}" -type f -name sc_ver.h -print -quit 2>/dev/null)"
+    [[ -r "${header}" ]] || return 1
+    awk '
+      /^[[:space:]]*#define[[:space:]]+SC_VERSION_MAJOR[[:space:]]+[0-9]+([[:space:]]|$)/ { major=$3 }
+      /^[[:space:]]*#define[[:space:]]+SC_VERSION_MINOR[[:space:]]+[0-9]+([[:space:]]|$)/ { minor=$3 }
+      /^[[:space:]]*#define[[:space:]]+SC_VERSION_PATCH[[:space:]]+[0-9]+([[:space:]]|$)/ { patch=$3 }
+      END {
+        if (major ~ /^[0-9]+$/ && minor ~ /^[0-9]+$/ && patch ~ /^[0-9]+$/) {
+          print major "." minor "." patch
+        } else {
+          exit 1
+        }
+      }
+    ' "${header}"
+}
+
+function Systemc_version_from_build() {
+    Systemc_version_from_tree "${PWD}"
+}
+
+function Registry_version() {
+    local directory="$1"
+    local config="${directory}/SystemCLanguageConfigVersion.cmake"
+    [[ -r "${config}" ]] || return 1
+    local version
+    version="$(sed -n 's/^[[:space:]]*set(PACKAGE_VERSION[[:space:]]*"\([0-9][0-9.]*\)".*$/\1/p' "${config}")"
+    printf '%s\n' "${version}" | head -n 1
+}
+
+function Check_registry_conflicts() {
+    local registry="${HOME}/.cmake/packages/SystemCLanguage" entry registered version target
+    [[ -d "${registry}" ]] || return 0
+    target="$(Systemc_version_from_tree "${PWD}")"
+    [[ -n "${target}" ]] || return 0
+    for entry in "${registry}"/*; do
+      [[ -f "${entry}" ]] || continue
+      registered="$(<"${entry}")"
+      [[ -n "${registered}" && -d "${registered}" ]] || continue
+      version="$(Registry_version "${registered}")"
+      [[ -n "${version}" && "${version}" != "${target}" ]] || continue
+      Set_color bold red bg-yellow; local alert="${COLOR}"
+      Set_color none; local reset="${COLOR}"
+      Echo "${alert}Warning: SystemC ${version} registry entry conflicts with incoming SystemC ${target}: ${registered}${reset}" >&2
+      if [[ "${STOP_ON_CONFLICT:-0}" == 1 ]]; then
+        Echo "${alert}Stopped before installation because --stop-on-conflict was requested.${reset}" >&2
+        return 1
+      fi
+      rm -f "${entry}"
+    done
+}
+
+function Step_Show() { [[ ${VERBOSITY:-0} != 0 ]] && Report_info "Step: $*"; }
+function Step_Next() { STEP_CURRENT=$(( ${STEP_CURRENT:-0} + 1 )); [[ -z "${STEP_MAX:-}" || ${STEP_CURRENT} -lt ${STEP_MAX} ]]; }
+
+function SetupLogdir() {
+    LOGDIR="${HOME}/logs"
+    mkdir -p "${LOGDIR}"
+    LOGFILE="${LOGDIR}/$(basename "${1:-build-systemc}").log"
+    : >"${LOGFILE}"
+    printf 'Logging to %s\n' "${LOGFILE}"
+}
+
+function ShowBuildOpts() {
+    printf 'Build options: source=%s install=%s version=%s builder=%s build-dir=%s\n' \
+      "${SRC}" "${CMAKE_INSTALL_PREFIX}" "${TOOL_VERS}" "${BUILDER}" "${BUILD_DIR}"
+}
+
+function ConfirmBuildOpts() {
+    [[ -n "${NOTREALLY:-}" || ${AUTO_CONFIRM:-0} == 1 ]] && return 0
+    ShowBuildOpts
+    local reply
+    while true; do
+      read -r -p "Confirm above options (y/n)? " reply
+      case "${reply}" in y|Y|yes) return 0 ;; n|N|no) return 1 ;; *) continue ;; esac
+    done
+}
+
+function HelpText() {
+    cat <<'EOF'
+Name
+----
+
+  build-systemc - build and install SystemC from GitHub source
+
+Synopsis
+--------
+
+  build-systemc [OPTIONS]
+
+Description
+-----------
+
+  Fetches the SystemC source, selects a version, configures it with CMake,
+  builds it, and (unless disabled) installs it under the selected prefix.
+
+Options
+-------
+
+  -h, --help          Display this help text.
+  -V, --version       Display the build-systemc version.
+  -n, --notreally     Show commands without executing them.
+  -q, --quiet         Suppress informational output.
+  -v, --verbose       Show informational output.
+  -clean, --clean     Remove and fetch the source again.
+  -no-fetch            Do not fetch or update source.
+  -no-compile         Skip compilation.
+  -no-install          Skip installation.
+  -s DIR, --src=DIR   Source parent directory (default: ~/.portable-scripts/src).
+  -i DIR, --install DIR, --install-dir DIR, --install-dir=DIR
+                      Installation prefix. An explicit path is used as-is;
+                      otherwise the default is /usr/local/apps/systemc-VERSION
+                      for root and ~/.local/apps/systemc-VERSION otherwise.
+  --systemc-version VERSION, --systemc-version=VERSION
+                      Git branch, tag, or commit to check out (default: main).
+  --generator=NAME    CMake generator, such as Ninja.
+  --build-dir=DIR     CMake build directory (default: target).
+  --build-type=TYPE   CMake build type (default: RelWithDebInfo).
+  -bd DIR, -bt TYPE, -gen NAME
+                      Legacy aliases for the corresponding long options.
+  --clang, --gcc      Select the corresponding compiler pair.
+  --stop-on-conflict  Stop before installation if the CMake SystemC registry
+                      contains a different SystemC version.
+
+Dependencies
+------------
+
+  Bash, Git, CMake, a C++ compiler, make or Ninja, tee, date, and Perl for
+  portable path resolution. Network access is required unless `--no-fetch` is
+  used. Installation also requires write permission to the selected prefix.
+
+Notes
+-----
+
+  1. The script is self-contained.
+  2. A failed checkout, configure, compile, or install command may leave partial
+  source or build directories. Review the selected source and install paths
+  before confirming
+  3. `--clean` removes the existing source tree.
+
+EOF
+}
+
+function GetBuildOpts() {
+    local arg
+    shift
+    CMAKE_CXX_STANDARD="${CMAKE_CXX_STANDARD:-17}"
+    CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-RelWithDebInfo}"
+    SRC="${SRC:-${TOOL_SRC}}"
+    if [[ -z "${CMAKE_INSTALL_PREFIX:-}" ]]; then
+      if [[ ${EUID} -eq 0 ]]; then
+        INSTALL_DIR="/usr/local/apps"
+      else
+        INSTALL_DIR="${HOME}/.local/apps"
+      fi
+    else
+      INSTALL_DIR="${CMAKE_INSTALL_PREFIX}"
+      INSTALL_DIR_EXPLICIT=1
+    fi
+    CMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
+    SYSTEMC_HOME="${SYSTEMC_HOME:-${INSTALL_DIR}}"
+    BUILDER="${BUILDER:-cmake}"
+    BUILD_DIR="${BUILD_DIR:-target}"
+    NOFETCH="${NOFETCH:-no}"; NOCOMPILE="${NOCOMPILE:-no}"; NOINSTALL="${NOINSTALL:-no}"
+    while [[ $# -gt 0 ]]; do
+      arg="$1"
+      case "${arg}" in
+        -h|-help|--help) HelpText; exit 0 ;;
+        -V) printf 'build-systemc version %s\n' "${BUILD_SYSTEMC_VERSION}"; exit 0 ;;
+        --version) printf 'build-systemc version %s\n' "${BUILD_SYSTEMC_VERSION}"; exit 0 ;;
+        -n|--notreally|--not-really) NOTREALLY=-n ;;
+        -q|--quiet) VERBOSITY=0 ;;
+        -v|--verbose) VERBOSITY=1 ;;
+        -clean|--clean) CLEAN=1 ;;
+        -no-fetch|--no-fetch|--nofetch) NOFETCH=yes ;;
+        -no-compile|--no-compile|--nocompile) NOCOMPILE=yes ;;
+        -no-install|--no-install|--noinstall) NOINSTALL=yes ;;
+        --stop-on-conflict) STOP_ON_CONFLICT=1 ;;
+        --clang) CC=clang; CXX=clang++ ;;
+        --gcc) CC=gcc; CXX=g++ ;;
+        --generator=*) GENERATOR="${arg#*=}" ;;
+        --build-dir=*) BUILD_DIR="${arg#*=}" ;;
+        --build-type=*) CMAKE_BUILD_TYPE="${arg#*=}" ;;
+        --src=*) SRC="${arg#*=}" ;;
+        --install=*|--apps=*|--install-dir=*) CMAKE_INSTALL_PREFIX="${arg#*=}"; INSTALL_DIR="${CMAKE_INSTALL_PREFIX}"; INSTALL_DIR_EXPLICIT=1 ;;
+        --install|--install-dir)
+          [[ $# -gt 1 ]] || { Report_fatal "Need argument for ${arg}"; return 1; }
+          CMAKE_INSTALL_PREFIX="$2"; INSTALL_DIR="$2"; INSTALL_DIR_EXPLICIT=1; shift ;;
+        --systemc-version=*) TOOL_VERS="${arg#*=}" ;;
+        --systemc-version)
+          [[ $# -gt 1 ]] || { Report_fatal "Need argument for ${arg}"; return 1; }
+          TOOL_VERS="$2"; shift ;;
+        --version=*)
+          Report_fatal "${arg%%=*} displays the build-systemc version; use --systemc-version for the SystemC checkout"
+          return 1 ;;
+        -bd|-bt|-bld|-gen|-i|-s|-sc)
+          [[ $# -gt 1 ]] || { Report_fatal "Need argument for ${arg}"; return 1; }
+          case "${arg}" in -bd) BUILD_DIR="$2";; -bt) CMAKE_BUILD_TYPE="$2";; -bld) BUILDER="$2";; -gen) GENERATOR="$2";; -i) CMAKE_INSTALL_PREFIX="$2"; INSTALL_DIR="$2"; INSTALL_DIR_EXPLICIT=1;; -s) SRC="$2";; -sc) SYSTEMC_HOME="$2";; *) return 1 ;; esac
+          shift ;;
+        *) ARGV+=("${arg}") ;;
+      esac
+      shift
+    done
+    export CC CXX
+    [[ -n "${CC:-}" ]] || { command -v clang >/dev/null 2>&1 && CC=clang || CC=gcc; }
+    [[ -n "${CXX:-}" ]] || { [[ "${CC}" == clang ]] && CXX=clang++ || CXX=g++; }
+    export CC CXX SRC CMAKE_INSTALL_PREFIX SYSTEMC_HOME BUILDER BUILD_DIR CMAKE_BUILD_TYPE GENERATOR NOFETCH NOCOMPILE NOINSTALL
+}
+
+function Create_and_Cd() { [[ $# == 1 ]] || return 1; _do mkdir -p "$1" && _do builtin cd "$1"; }
+
+function GetSource_and_Cd() {
+    local dir="$1" url="$2"
+    [[ ${CLEAN:-0} == 1 ]] && _do rm -rf "${dir}"
+    if [[ "${NOFETCH}" == yes ]]; then _do builtin cd "${dir}"; return; fi
+    if [[ -d "${dir}/.git" ]]; then _do git -C "${dir}" pull --no-edit; else _do git clone "${url}" "${dir}"; fi
+    _do builtin cd "${dir}"
+}
+
+function Select_version() { [[ -n "${1:-}" ]] && _do git checkout "$1" .; }
+function Configure_tool() {
+    _do rm -rf "${BUILD_DIR}"
+    local -a options=(-B "${BUILD_DIR}" -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX}" -DCMAKE_CXX_STANDARD="${CMAKE_CXX_STANDARD}" -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}")
+    [[ -n "${GENERATOR:-}" ]] && options+=(-G "${GENERATOR}")
+    _do cmake "${options[@]}"
+}
+function Compile_tool() { [[ "${NOCOMPILE}" == yes ]] && return 0; _do cmake --build "${BUILD_DIR}"; }
+function Install_tool() {
+    [[ "${NOINSTALL}" == yes ]] && return 0
+    _do cmake --install "${BUILD_DIR}" --prefix "${SYSTEMC_HOME}"
+}
+
+Build_systemc "$0" "$@"
 
 # vim:nospell
diff --git a/tools/bin/tool-versions b/tools/bin/tool-versions
--- a/tools/bin/tool-versions
+++ b/tools/bin/tool-versions
@@ -1,178 +1,434 @@
 #!/usr/bin/env bash
 #
 #$Info: tool-versions - displays version information for selected development tools. $
+#
+# Runtime requirements are checked after option parsing. macOS uses GNU
+# utilities installed by Homebrew for commands such as sed and tar.
+
+export CC CXX
+TOOL_NAME="${0##*/}"
+TOOL_VERS=1.3.1
 
 function Tool_versions()
 {
-  local EXTRA TOOLS
+  # Defaults
+  local EXTRA QUIET SORT
+  local -a TOOLS EXTRAS
+  export NOCOLOR CXX CC
   EXTRA=0
+  QUIET=0
+  SORT=1
   TOOLS=()
+  # Color support
+  local CRED="" CGRN="" CYLW="" CBLU="" CMAG="" CCYN="" BOLD="" NONE=""
+  if [[ "${NOCOLOR}" != 1 ]]; then
+    # shellcheck disable=SC2034
+    CRED="[91m" CGRN="[92m" CYLW="[93m" CBLU="[94m" CMAG="[95m" CCYN="[96m" BOLD="[1m" NONE="[0m"
+  fi
   while [[ $# != 0 ]]; do
     case "$1" in
       -h|--help)
+        if [[ $# != 1 ]]; then
+          echo "Error: --help must be the only option" >&2
+          exit 1
+        fi
         cat <<EOT
 NAME
 ----
 
-  $0 - Display the versions of tools
+  ${TOOL_NAME} - Display the versions of tools
 
 SYNOPSIS
 --------
 
-  $0 -h|--help
-  $0 --version
-  $0
-  $0 [-a|--extra]
-  $0 TOOL...
+  ${TOOL_NAME} -h|--help
+  ${TOOL_NAME} -V|--version
+  ${TOOL_NAME} [OPTIONS] [TOOL...]
 
 DESCRIPTION
 -----------
 
 This script is useful to produce a quick list of tools in your environment. You can use when creating a bug report or when creating information about how something was tested.
 
+OPTIONS
+-------
+
+| OPTION    | SHORT | DESCRIPTION                        |
+| :-----    | :---: | :----------                        |
+| --color   |  -C   | Use color (default)                |
+| --extras  |  -x   | Show extra tools                   |
+| --help    |  -h   | Display this help                  |
+| --loud    |  -l   | Yell about missing tools (default) |
+| --no-color, --nocolor |  -N   | No color                    |
+| --quiet   |  -q   | Don't complain about missing tools |
+| --no-sort |  -n   | Do not sort the tool list          |
+| --sort    |  -s   | Sort the tool list (default)       |
+| --version |  -V   | Show version of this script        |
+
+DEPENDENCIES
+------------
+
+- Bash: required to interpret this script; Bash 3.2 or newer is supported.
+- date: required for the host-information timestamp unless \`NODATE\` is set.
+- Perl (perl or perl5): required to parse Linux distribution information and
+  filter tool version output.
+- uname (guname on macOS): required for host information.
+- sort: required to sort the tool list; the portable line-based mode works with
+  BSD sort on macOS and GNU sort on Linux.
+- sw_vers: required on macOS for the operating-system version.
+- The commands listed in the default and --extras tool lists are optional
+  targets, not script dependencies. They need not be installed, but missing
+  targets are reported unless --quiet is selected.
+
+CONFLICTS AND PLATFORM NOTES
+----------------------------
+
+- macOS ships BSD utilities. If Homebrew is not installed, use
+  /bin/bash -c "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)".
+  Then install GNU dependencies with: brew install coreutils gnu-sed gnu-tar
+  perl. Ensure Homebrew's bin directory is in PATH (brew shellenv can do this).
+- On macOS, \`/usr/bin/sed\` is already available. GNU sed from Homebrew supplies
+  \`gsed\` for systems where GNU sed's version output is desired; coreutils
+  supplies \`guname\`, and gnu-tar supplies \`gtar\`. The script prefers these GNU
+  names when they are installed; the regular BSD sort is sufficient here.
+- Ubuntu and other GNU/Linux systems normally provide the required utilities;
+  minimal installations may need packages such as perl and coreutils.
+- WSL is supported when wsl.exe is visible in PATH; it is optional and only
+  adds a WSL host label.
+- MinGW/MSYS/Cygwin Bash environments may have different tool names and
+  version-output formats. The script does not require Windows tools, but the
+  requested development tools must be available in PATH.
+- Tool version output is filtered by tool-specific patterns, so vendor or
+  localized output can be omitted even when a command succeeds.
+
 EOT
-        exit
+        exit 0
         ;;
-      -a|--extra[s]?) EXTRA=1 ;;
-      --version) echo "version 1.0" ; exit ;;
-      -*) echo "Error: Uknown option: $1"; exit 1 ;;
-      *) TOOLS+=("$1") ;;
+      -x|--extras)   EXTRA=1 ;;
+      -C|--color)    NOCOLOR=0 CRED="[91m" CGRN="[92m" BOLD="[1m" NONE="[0m" ;;
+      -l|--loud)     QUIET=0 ;;
+      -N|--no-color|--nocolor) NOCOLOR=1 CRED="" CGRN="" BOLD="" NONE="" ;;
+      -n|--no-sort)  SORT=0 ;;
+      -q|--quiet)    QUIET=1 ;;
+      -s|--sort)     SORT=1 ;;
+      -V|--version)
+        if [[ $# != 1 ]]; then
+          echo "Error: --version must be the only option" >&2
+          exit 1
+        fi
+        echo "${TOOL_NAME} version ${TOOL_VERS}"
+        exit 0
+        ;;
+      -*)            echo "Error: Unknown option: $1" >&2; exit 1 ;;
+       *)            TOOLS+=("$1") ;;
     esac
     shift
   done
 
+  local PERL5 PYTHON3 SED TAR UNAME SORT_COMMAND
+  PERL5="perl"
+  # shellcheck disable=SC2312
+  if [[ -n "$(builtin command -v perl5 )" ]]; then
+    PERL5="perl5"
+  fi
+  if ! builtin command -v "${PERL5}" >/dev/null 2>&1; then
+    PERL5="perl5"
+  fi
+  # Python 3 may be installed as either `python3` or `python`; verify the
+  # selected command's version output when it is reported below.
+  PYTHON3="python"
+  # shellcheck disable=SC2312
+  if [[ -n "$(builtin command -v python3 )" ]]; then
+    PYTHON3="python3"
+  fi
+  SED="sed"
+  # shellcheck disable=SC2312
+  if [[ -n "$(builtin command -v gsed )" ]]; then
+    SED="gsed"
+  fi
+  TAR="tar"
+  # shellcheck disable=SC2312
+  if [[ -n "$(builtin command -v gtar )" ]]; then
+    TAR="gtar"
+  fi
+  UNAME="uname"
+  # shellcheck disable=SC2312
+  if [[ -n "$(builtin command -v guname )" ]]; then
+    UNAME="guname"
+  fi
+  if ! builtin command -v "${UNAME}" >/dev/null 2>&1; then
+    echo "Error: Missing required dependency: ${UNAME}" >&2
+    return 1
+  fi
+  local HOSTOS
+  HOSTOS="$("${UNAME}" -s 2>/dev/null)"
+  if [[ -z "${HOSTOS}" ]]; then
+    echo "Error: Unable to determine the host operating system" >&2
+    return 1
+  fi
+  # Newline sorting is sufficient because tool names cannot contain newlines;
+  # unlike sort -z, it works with both BSD sort and GNU sort.
+  SORT_COMMAND="sort"
+
+  # Check the commands that the script itself, rather than a listed target,
+  # must execute.  Do this before producing output to avoid partial reports.
+  local REQUIRED_COMMAND
+  local -a REQUIRED_COMMANDS
+  REQUIRED_COMMANDS=( "${PERL5}" "${UNAME}" "${SORT_COMMAND}" )
+  if [[ -z "${NODATE}" ]]; then
+    REQUIRED_COMMANDS+=( date )
+  fi
+  for REQUIRED_COMMAND in "${REQUIRED_COMMANDS[@]}"; do
+    if ! builtin command -v "${REQUIRED_COMMAND}" >/dev/null 2>&1; then
+      echo "Error: Missing required dependency: ${REQUIRED_COMMAND}" >&2
+      return 1
+    fi
+  done
+
+  # Check macOS-only dependencies before producing any report output.
+  if [[ "${HOSTOS}" == "Darwin" ]] && ! builtin command -v sw_vers >/dev/null 2>&1; then
+    echo "Error: Missing required dependency: sw_vers" >&2
+    return 1
+  fi
+
+      
   # Default tools
-  local -a TOOLS EXTRAS
   if [[ "${#TOOLS[@]}" == 0 ]]; then
     TOOLS=(
-      systemc-version
-      g++
+      autoconf
+      bash
+      cargo
       clang++
       cmake
-      autoconf
-      make
-      gmake
-      ninja
+      g++
       gdb
+      git
+      gmake
+      grep
       lldb
-      bash
-      zsh
+      make
+      ninja
+      "${PERL5}"
+      "${PYTHON3}"
+      rustc
+      rustup
+      systemc-version
     )
   fi
   EXTRAS=(
     ag 
+    build
     clang-format
     clang-tidy
-    git
-    grep
+    croc
+    find_extern
+    gh
+    gtree
+    gzip
+    marktext
+    rg
     rsync
     shellcheck
+    "${SED}"
+    "${TAR}"
+    tree
+    "${UNAME}"
+    unzip
+    zip
+    zsh
   )
 
-  local GREP UNAME
-  GREP="grep"
-  # shellcheck disable=SC2312
-  if [[ -n "$(command -v ggrep )" ]]; then
-    GREP="ggrep"
-  fi
-  UNAME="uname"
-  # shellcheck disable=SC2312
-  if [[ -n "$(command -v guname )" ]]; then
-    UNAME="guname"
-  fi
-
   if [[ ${EXTRA} == 1 ]]; then
-    TOOLS=("${TOOLS[@]}" "${EXTRAS[@]}")
+    TOOLS+=( "${EXTRAS[@]}" )
   fi
 
   #-------------------------------------------------------------------------------
   # Filters
   #-------------------------------------------------------------------------------
-  local FILTER
-  FILTER='AUTHORS'
-  FILTER+='|Capabilities'
-  FILTER+='|Copyright'
-  FILTER+='|Features'
-  FILTER+='|internal'
-  FILTER+='|Install'
-  FILTER+='|License'
-  FILTER+='|Licence'
-  FILTER+='|licenses'
-  FILTER+='|lzma'
-  FILTER+='|maintained'
-  FILTER+='|rsync.samba'
-  FILTER+='|ShellCheck'
-  FILTER+='|Swift'
-  FILTER+='|There'
-  FILTER+='|This'
-  FILTER+='|Thread'
-  FILTER+='|Target'
-  FILTER+='|website'
-  FILTER+='|welcome'
-  FILTER+='|Written'
+  local FILTER_OUT REPORT DATE_OUTPUT DATE_STATUS
+  REPORT="----------------------------------------\n"
+  FILTER_OUT='AUTHORS'
+  FILTER_OUT+='|Capabilities'
+  FILTER_OUT+='|Copyright'
+  FILTER_OUT+='|Features'
+  FILTER_OUT+='|free.software'
+  FILTER_OUT+='|internal'
+  FILTER_OUT+='|Install'
+  FILTER_OUT+='|License'
+  FILTER_OUT+='|Licence'
+  FILTER_OUT+='|licenses'
+  FILTER_OUT+='|lzma'
+  FILTER_OUT+='|maintained'
+  FILTER_OUT+='|Packaged by Debian'
+  FILTER_OUT+='|rsync.samba'
+  FILTER_OUT+='|rsync version'
+  FILTER_OUT+='|ShellCheck'
+  FILTER_OUT+='|Swift'
+  FILTER_OUT+='|There'
+  FILTER_OUT+='|Thread'
+  FILTER_OUT+='|Target'
+  FILTER_OUT+='|website'
+  FILTER_OUT+='|welcome'
+  FILTER_OUT+='|Written'
 
-  echo "----------------------------------------"
-  date
+  export NODATE
+  if [[ -z "${NODATE}" ]]; then
+    DATE_OUTPUT="$(date 2>&1)"
+    DATE_STATUS=$?
+    if [[ ${DATE_STATUS} != 0 ]]; then
+      echo "Error: 'date' failed" >&2
+      return 1
+    fi
+    REPORT+="${DATE_OUTPUT}\n"
+  fi
 
   #-------------------------------------------------------------------------------
   # Announce the Host information
   #-------------------------------------------------------------------------------
-  local HOSTOS OS PERLSCRIPT
-  HOSTOS="$("${UNAME}" -s)"
+  local OS PERLSCRIPT HOST_OUTPUT HOST_STATUS
   case "${HOSTOS}" in
-    Darwin) 
-      "${UNAME}" -moprv
+    Darwin)
+      HOST_OUTPUT="$("${UNAME}" -moprv 2>&1)"
+      HOST_STATUS=$?
+      if [[ ${HOST_STATUS} != 0 ]]; then
+        echo "Error: '${UNAME} -moprv' failed" >&2
+        return 1
+      fi
       OS="$(sw_vers --productName) "
       OS+="$(sw_vers --productVersion)"
       OS+="$(sw_vers --productVersionExtra) "
       OS+="$(sw_vers --buildVersion) "
-      echo "${OS}"
+      REPORT+="${HOST_OUTPUT}\n${OS}\n"
       ;;
     *)
-      "${UNAME}" -smoprv
+      HOST_OUTPUT="$("${UNAME}" -smoprv 2>&1)"
+      HOST_STATUS=$?
+      if [[ ${HOST_STATUS} != 0 ]]; then
+        echo "Error: '${UNAME} -smoprv' failed" >&2
+        return 1
+      fi
+      REPORT+="${HOST_OUTPUT}\n"
       # shellcheck disable=SC2312
-      if [[ -n "$(command -v wsl.exe )" ]]; then
-        echo -n "WSL "
+      if [[ -n "$(builtin command -v wsl.exe )" ]]; then
+        REPORT+="WSL "
       fi
       if [[ -r /etc/os-release ]]; then
+        # Accept both quoted and unquoted PRETTY_NAME values from os-release.
         # shellcheck disable=SC2034,SC2016
-        PERLSCRIPT='if(m{PRETTY_NAME="([^"]+)"}){$os=$1;$os=~s{Oracle}{CentOS};print $os;}'
-        perl -lne "${PERLSCRIPT}" /etc/os-release
+        PERLSCRIPT='if(m{^PRETTY_NAME="?([^"\n]+)"?$}){$os=$1;$os=~s{Oracle}{CentOS};print $os;}'
+        local DISTRIBUTION DISTRIBUTION_STATUS
+        DISTRIBUTION="$(${PERL5} -lne "${PERLSCRIPT}" /etc/os-release)"
+        DISTRIBUTION_STATUS=$?
+        if [[ ${DISTRIBUTION_STATUS} != 0 ]]; then
+          echo "Error: Unable to determine the Linux distribution" >&2
+          return 1
+        fi
+        REPORT+="${DISTRIBUTION}\n"
       fi
       ;;
   esac
 
-  echo "........................................"
+  REPORT+="........................................\n"
+
+  #-------------------------------------------------------------------------------
+  # Sort
+  #-------------------------------------------------------------------------------
+  if [[ ${SORT} == 1 ]]; then
+    local -a SORTED=()
+    local ELEMENT SORTED_OUTPUT SORT_STATUS
+    SORTED_OUTPUT="$(printf '%s\n' "${TOOLS[@]}" | "${SORT_COMMAND}")"
+    SORT_STATUS=$?
+    if [[ ${SORT_STATUS} != 0 ]]; then
+      echo "Error: Unable to sort the tool list" >&2
+      return 1
+    fi
+    while IFS= read -r ELEMENT; do
+      [[ -n "${ELEMENT}" ]] && SORTED+=("${ELEMENT}")
+    done <<< "${SORTED_OUTPUT}"
+    TOOLS=("${SORTED[@]}")   
+  fi
 
   #-------------------------------------------------------------------------------
   # Display each of the tools
   #-------------------------------------------------------------------------------
-  local TOOL EXISTS PATTERN
+  local TOOL EXISTS PATTERN SUBST VERSION_OPTION TOOL_LABEL
   for TOOL in "${TOOLS[@]}"; do
-    EXISTS="$(command -v "${TOOL}")"
+    VERSION_OPTION=--version
+    EXISTS="$(builtin command -v "${TOOL}")"
     PATTERN=""
+    SUBST="s/This is perl/Perl/"
     if [[ -n "${EXISTS}" ]]; then
       case "${TOOL}" in
-        g[+][+]|clang|bash|zsh) PATTERN="${TOOL}" ;;
-        make|gmake) PATTERN="Make" ;;
-        clang-tidy|git|rsync|shellcheck) PATTERN="version" ;;
-        *)   PATTERN+="" ;;
+        ag)    PATTERN="ag version" ;;
+        bash)  PATTERN="${TOOL}" ;;
+        build) PATTERN="build version" ;;
+        clang++) PATTERN="clang version" ;;
+        clang-tidy) PATTERN="version" ;;
+        clang-format) PATTERN="version" ;;
+        clang) PATTERN="${TOOL}" ;;
+        g[+][+]) PATTERN="${TOOL}" ;;
+        gh)    PATTERN="gh version" ;;
+        git)   PATTERN="version" ;;
+        gmake) PATTERN="Make" ;;
+        gsed)  PATTERN="[(]GNU sed[)]" ;;
+        gzip)  PATTERN="gzip" ;;
+        make)  PATTERN="Make" ;;
+        perl)  PATTERN="version" ;;
+        python|python3) PATTERN="Python 3" ;;
+        rg)    PATTERN="ripgrep" ;;
+        rsync) PATTERN="version" ;;
+        sed)   PATTERN="[(]GNU sed[)]" ;;
+        shellcheck) PATTERN="version" ;;
+        tar)   PATTERN="bsdtar" ;;
+        unzip) PATTERN="modifications" VERSION_OPTION=-v ;;
+        zip)   PATTERN="This is " SUBST="s/This is //" ;;
+        rustup) PATTERN="^rustup[[:space:]]" ;;
+        zsh)   PATTERN="${TOOL}" ;;
       esac
-      echo -n "${TOOL} - "
-      # shellcheck disable=SC2312
-      "${TOOL}" --version 2>/dev/null \
-      | "${GREP}" -E "${PATTERN}" \
-      | "${GREP}" -v -E "(${FILTER})" \
-      | "${GREP}" -v '^$' \
-      ;
-    else
-      echo "${TOOL} - MISSING"
+      TOOL_LABEL="${CGRN}${TOOL}${NONE} - "
+      # Buffer each command so a failed version probe can be distinguished
+      # from a valid command whose output simply has no matching filter.
+      local VERSION_OUTPUT VERSION_STATUS
+      VERSION_OUTPUT="$("${TOOL}" "${VERSION_OPTION}" 2>&1)"
+      VERSION_STATUS=$?
+      if [[ ${VERSION_STATUS} != 0 ]]; then
+        REPORT+="${CRED}${TOOL} - ${BOLD}FAILED${NONE}\n"
+        continue
+      fi
+      # A command named `python` is acceptable only when it identifies as
+      # Python 3; this catches legacy Python 2 installations explicitly.
+      if [[ "${TOOL}" == "python" || "${TOOL}" == "python3" ]] &&
+        [[ ! "${VERSION_OUTPUT}" =~ Python[[:space:]]3 ]]; then
+        REPORT+="${CRED}${TOOL} - ${BOLD}FAILED (Python 3 required)${NONE}\n"
+        continue
+      fi
+      local FILTERED_OUTPUT FILTER_STATUS
+      FILTERED_OUTPUT="$(printf '%s\n' "${VERSION_OUTPUT}" \
+        | "${PERL5}" -ne "next unless m/${PATTERN}/; next if m/(${FILTER_OUT})/ or m/^$/; ${SUBST}; print")"
+      FILTER_STATUS=$?
+      if [[ ${FILTER_STATUS} != 0 ]]; then
+        REPORT+="${CRED}${TOOL} - ${BOLD}FAILED${NONE}\n"
+      else
+        REPORT+="${TOOL_LABEL}${FILTERED_OUTPUT}\n"
+      fi
+    elif [[ ${QUIET} != 1 ]]; then
+      REPORT+="${CRED}${TOOL} - ${BOLD}MISSING${NONE}\n"
     fi
   done
+  if [[ -n "${CXX}" ]]; then
+    REPORT+="${CCYN}export CXX=${CXX}${NONE}\n"
+  fi
+  if [[ -n "${CC}" ]]; then
+    REPORT+="${CCYN}export CC=${CC}${NONE}\n"
+  fi
 
-  echo "----------------------------------------"
+  REPORT+="----------------------------------------\n"
+  if [[ ${EXTRA} == 0 ]]; then
+    REPORT+="${CCYN}HINT: More tools can be checked with --extras${NONE}\n"
+  fi
+  printf '%b' "${REPORT}"
 }
 
 Tool_versions "$@"
 
-  # vim:nospell
+# vim:nospell
